debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: mint
    password: test1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 해당옵션이 true 일경우 data.sql 실행
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always # data.sql 실행시점 지정
  data.rest:
    base-path: /api
    detection-strategy: annotated